### PR TITLE
merged CSharp BotAuth with existing Node BotAuth

### PR DESCRIPTION
**Pull request by richdizz**
I didn't touch the Node project...just moved it to a subfolder like the other bot projects in the Microsoft org's github

### CODE REVIEW

**Comment by mattdot** [comment]
I need to check if some of the node paths need to be modified before merging this.  They might not expect to be under /Node.  Probably later in the week.  Thanks for submitting this!

**Review by EricDahlvang — CHANGES_REQUESTED** [review]
Please update the CallbackController to use IBotDataStore 

scope.Resolve< IStateClient >(); will resolve to the default state client, and is being deprecated.

scope.Resolve< IBotDataStore < BotData > >(); resolves to the same implementation as the context state methods.

**Comment by EricDahlvang** [comment]
Can we get this updated, merged and released please?  

It would also be helpful to reference this repository from the readme of https://github.com/richdizz/BotAuth and https://github.com/MicrosoftDX/AuthBot

**Comment by mattdot** [comment]
I think part of what happened is that the .travis.yml file got moved so travisci couldn't build the repo

**Review by EricDahlvang — APPROVED** [review]

**Pull request merged**
